// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL2cjvqisurWy6b9yXCwIhPxLvNw4OL7E',
    appId: '1:863069402685:web:13a2b9cf0e7f75d7361c54',
    messagingSenderId: '863069402685',
    projectId: 'eagle-plus-app',
    authDomain: 'eagle-plus-app.firebaseapp.com',
    storageBucket: 'eagle-plus-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxQVI2Bbosh8kfGS9tJJ81PV8tizwxUqU',
    appId: '1:863069402685:android:0cc3f1e1f68db215361c54',
    messagingSenderId: '863069402685',
    projectId: 'eagle-plus-app',
    storageBucket: 'eagle-plus-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZv3NngLMg-HDlSElwmOQKaQnTDKIohzU',
    appId: '1:863069402685:ios:65cfd9fe5fea3591361c54',
    messagingSenderId: '863069402685',
    projectId: 'eagle-plus-app',
    storageBucket: 'eagle-plus-app.appspot.com',
    iosClientId: '863069402685-u42mos2i253adprv48mduqjeg03tuvr9.apps.googleusercontent.com',
    iosBundleId: 'com.example.eaglePlusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZv3NngLMg-HDlSElwmOQKaQnTDKIohzU',
    appId: '1:863069402685:ios:65cfd9fe5fea3591361c54',
    messagingSenderId: '863069402685',
    projectId: 'eagle-plus-app',
    storageBucket: 'eagle-plus-app.appspot.com',
    iosClientId: '863069402685-u42mos2i253adprv48mduqjeg03tuvr9.apps.googleusercontent.com',
    iosBundleId: 'com.example.eaglePlusApp',
  );
}
